#include "stm32f10x.h"

int main() {
  RCC->APB2ENR |= (RCC_APB2ENR_IOPAEN | RCC_APB2ENR_AFIOEN);
	
	GPIOA->CRL |= GPIO_CRL_MODE0;
  GPIOA->CRL &= ~GPIO_CRL_CNF0;
  GPIOA->CRL |= GPIO_CRL_CNF0_1;
	
  GPIOA->CRL |= GPIO_CRL_MODE1;
  GPIOA->CRL &= ~GPIO_CRL_CNF1;
  GPIOA->CRL |= GPIO_CRL_CNF1_1;
	
	GPIOA->CRL |= GPIO_CRL_MODE2;
  GPIOA->CRL &= ~GPIO_CRL_CNF2;
  GPIOA->CRL |= GPIO_CRL_CNF2_1;
	
	GPIOA->CRL |= GPIO_CRL_MODE3;
  GPIOA->CRL &= ~GPIO_CRL_CNF3;
  GPIOA->CRL |= GPIO_CRL_CNF3_1;
	
  RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->CCMR1|=(TIM_CCMR1_OC1M_0| TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC2M_0| TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_2);
	TIM2->CCMR2|=(TIM_CCMR2_OC3M_0 | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC4M_0 | TIM_CCMR2_OC4M_1 | TIM_CCMR2_OC4M_2);
	
	TIM2->CCER |= (TIM_CCER_CC1E|TIM_CCER_CC2E|TIM_CCER_CC3E|TIM_CCER_CC4E);
	
  TIM2->ARR = 4000 - 1;
	TIM2->CCR1 = 1000;
  TIM2->CCR2 = 2000;
	TIM2->CCR3 = 2500;
	TIM2->CCR4 = 3000;
	TIM2->DIER |= TIM_DIER_UIE;
	//IC_EnableIRQ(TIM2_IRQn);
  TIM2->CR1 |= TIM_CR1_CEN;	

  while(1);
}

//id TIM2_IRQHandler() 
//
// TIM2->SR&=~TIM_SR_UIF;
//}
